server:
  port: 8081

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: -
    password: -
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${user.dir}/img
      
logging:
  file:
    name: ${user.dir}/log/test.log
    max-history: 7
    max-size: 10MB
  level:
    root: warn
    com.mungta.user: debug
    com.mungta.user.api: debug
    com.mungta.user.auth: debug
    com.mungta.user.config: info
    com.mungta.user.domain: info
    com.mungta.user.dto: info
    com.mungta.user.kafka: info

