server:
  port: 8081

---

spring:
  profiles: default
  datasource:
    jdbc-url: jdbc:mysql://mungta-user-db.mysql.database.azure.com:3306/user_dev?serverTimezone=Asia/Seoul&validationQuery="select 1"
    username: mungta
    password: andxk12#$
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: mungta-user
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
#    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: -
    password: -
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${user.dir}/img

logging:
  file:
    name: ${user.dir}/log/test.log
    max-history: 7
    max-size: 10MB
  level:
    root: warn
    com.mungta.user: debug
    com.mungta.user.api: debug
    com.mungta.user.auth: debug
    com.mungta.user.config: info
    com.mungta.user.domain: info
    com.mungta.user.dto: info
    com.mungta.user.kafka: info
